title: Termina Plex Jekyll Theme
author:
  name: Termina Plex
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Site Description

# Build settings
permalink: pretty

# Pagination
paginate: 4
paginate_path: "/blog/page:num"

# If you clone the Termina Plex repo and build locally, use this setting.
# theme: termina-plex

# If you want to use this theme for sites hosted using GitHub Pages, use the following setting and
# add a line comment on "theme: termina-plex" above.
remote_theme: questionlp/termina-plex

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

kramdown:
  smart_quotes: apos,apos,quot,quot

# Theme-specific settings

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Termina Plex specific settings
termina-plex:
  date_format: "%d %b %Y"
  long_date_format: "%d %B %Y %H:%M:%S"

  username: theme
  hostname: termina-plex

  header_links:
    - { name: About, url: "/about" }
    - { name: Blog, url: "/blog" }

  social_links:
    - { name: GitHub, url: "https://github.com/questionlp/termina-plex" }
    - { name: Jekyll, url: "https://jekyllrb.com" }
